### ISSUE TITLE
Single node deployment. Exit Code 2

### ISSUE THREAD

**Issue by JamesJoe-C** [m3db/m3db-operator#285]
install.sh:
```
#!/bin/bash

CWD=$(cd $(dirname $0)/; pwd)
cd $CWD/..

systemctl stop m3dbnode

mkdir -p /opt/data/{m3db,m3kv}
mkdir -p /opt/m3db/{bin,etc}

cp -af ./bin/* /opt/m3db/bin/
cp -af ./etc/*.yml /opt/m3db/etc/

sysctl -w vm.max_map_count=3000000
sysctl -w vm.swappiness=1
sysctl -w fs.file-max=3000000
sysctl -w fs.nr_open=3000000
# echo "${USER} hard nofile 3000000" >> /etc/security/limits.conf
# Edit /etc/security/limits.conf file and allow the user under which asterisk runs to modify the ulimit to a higher value.
# <username> hard nofile <number>
ulimit -n 3000000

grep 'vm.max_map_count = 3000000' /etc/sysctl.conf || cat >> /etc/sysctl.conf <<'EOF'
# m3db
vm.max_map_count = 3000000
vm.swappiness = 1
fs.file-max = 3000000
fs.nr_open = 3000000
EOF

sudo cp -a ./systemd/m3dbnode.service /usr/lib/systemd/system/m3dbnode.service
systemctl daemon-reload
systemctl start m3dbnode
systemctl status m3dbnode
```
m3dbnode.service:
```
[Unit]
Description="M3DB Timeseries Database"
Documentation=https://docs.m3db.io/
After=network.target

[Service]
WorkingDirectory=/opt/m3db
#EnvironmentFile=/opt/run/m3db/etc/m3dbnode.env
Type=simple
ExecStart=/opt/m3db/bin/m3dbnode -f /opt/m3db/etc/m3dbnode.yml
Restart=on-failure
RestartSec=10s
SuccessExitStatus=0

# May not be honored if higher than kernel limit (sysctl fs.file-max) or process
# limit (sysctl fs.nr_open). Also may not be honored if lower than systemd limit
# (system.conf) or systemd user limit (user.conf).
LimitNOFILE=3000000

[Install]
WantedBy=multi-user.target
```

ERROR LOG:
```
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4653 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0xacc3e15cacc3e15c, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4654 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0x70af990270af9902, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4655 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0x2841541c2841541c, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4656 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0x5a102ccc5a102ccc, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4657 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0xe3aafa8fe3aafa8f, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4658 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0xe064fce8e064fce8, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4659 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0x64a6fba264a6fba2, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
3月 17 13:56:25 localhost m3dbnode[2512755]: goroutine 4660 [chan receive]:
3月 17 13:56:25 localhost m3dbnode[2512755]: github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc0004c41c0, 0x0, 0xa7c87967a7c87967, 0xc000424180, 0x1c82101)
3月 17 13:56:25 localhost m3dbnode[2512755]:         /home/odin/steveyubo/m3/src/x/sync/pooled_worker_pool.go:145 +0x151
3月 17 13:56:25 localhost m3dbnode[2512755]: created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
3月 17 13:56:26 localhost systemd[1]: m3dbnode.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
3月 17 13:56:26 localhost systemd[1]: m3dbnode.service: Failed with result 'exit-code'.
```

**Comment by gibbscullen** [comment]
@JamesJoe-C -- Where did you get the install.sh from? Also, have you tried looking at our quickstart guides (linked here: https://m3db.io/docs/quickstart/binaries/)?
